name: Windows-Build

on:
  pull_request:
  push:
    paths-ignore:
      - '.github/workflows/windows-build.yml'
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]
        arch: [x64]
        mode: [debug, releasedbg]

    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    steps:
    - uses: actions/checkout@v2

    - name: Set xmake env
      run: echo "$(pwd)/xmake-global" >> $XMAKE_GLOBALDIR

    # Install xmake
    - name: Setup xmake
      uses: xmake-io/github-action-setup-xmake@v1

    # Install Qt (required for map editor)
    - name: Install Qt
      uses: jurplel/install-qt-action@v2

    # Update xmake repository (in order to have the file that will be cached)
    - name: Update xmake repository
      run: xmake.exe repo --update

    # Cache xmake dependencies
    - uses: actions/cache@v2
      with:
        path: xmake-global\packages
        key: ${{ runner.os }}-${{ matrix.arch }}-${{ matrix.mode }}-${{ hashFiles('xmake.lua', 'xmake-repo') }}-${{ hashFiles('xmake-global\xmake.conf') }}-${{ hashFiles('xmake-global\repositories\**') }}

    # Setup compilation mode and install project dependencies
    - name: Configure xmake and install dependencies
      run: xmake.exe config --arch=${{ matrix.arch }} --mode=${{ matrix.mode }} --yes --verbose

    # Build the game
    - name: Build BurgWar
      run: xmake.exe

    # Install the result files
    - name: Install BurgWar
      run: xmake.exe install -vo package

    # Compile the map to the package
    - name: Compile map
      run: ./maptool.exe --compile beta_map.bmap ../../maps/beta_map
      working-directory: package/bin
  
    # Upload artifacts
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.mode }}
        path: package/bin
