name: Windows-Build

on:
  pull_request:
  push:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]
        arch: [x64]
        mode: [debug, release]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    # Install xmake
    - name: Setup xmake
      uses: xmake-io/github-action-setup-xmake@v1

    # Install Qt (required for map editor)
    - name: Install Qt
      uses: jurplel/install-qt-action@v2

    # Setup compilation mode and install project dependencies
    - name: Configure xmake and install dependencies
      run: xmake.exe config --arch=${{ matrix.arch }} --mode=${{ matrix.mode }} --yes --verbose

    # Build the game
    - name: Build BurgWar
      run: xmake.exe

    # Upload artifacts
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.mode }}
        path: bin/windows_${{ matrix.arch }}-${{ matrix.mode }}
